/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 584fadf6b7847cf400bd441af153cf88)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	SUPABASE_ORIGIN: "https://nkvmpjznvkqmgcposaup.supabase.co";
	VITE_SUPABASE_URL: string;
	VITE_SUPABASE_PUBLISHABLE_KEY: string;
	VITE_CLOUD_MODE: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
